# Generated by Django 4.2 on 2024-08-27 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_whiteboard_whiteboardjoinrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whiteboardjoinrequest',
            name='student',
        ),
        migrations.RemoveField(
            model_name='whiteboardjoinrequest',
            name='whiteboard',
        ),
        migrations.DeleteModel(
            name='Whiteboard',
        ),
        migrations.DeleteModel(
            name='WhiteboardJoinRequest',
        ),
    ]
