# Generated by Django 4.2 on 2024-08-01 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_post_status_update', 'Can post status update')]},
        ),
    ]
