# Generated by Django 4.2 on 2024-08-01 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'permissions': [('can_manage_courses', 'Can manage courses'), ('can_access_student_records', 'Can access student records')]},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'permissions': [('can_leave_feedback', 'Can leave feedback')]},
        ),
    ]
